# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Basys3Master.xdc

# IP: ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_2 || ORIG_REF_NAME==blk_mem_gen_2} -quiet] -quiet

# IP: ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# XDC: ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc

# XDC: ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc
